### ISSUE TITLE
Not downloading Gfycat links

### ISSUE THREAD

**Issue by Givblod** [Seklfreak/discord-image-downloader-go#116]
Hello. I set up the downloader it's working alright but each time the downloader requests 100 messages, it only downloads the discord attachments on the channel. Skipping all the gfycat links on the way historically going back. Something wrong with gfycat link downloading or will it start downloading gfycat links after the discord attachments are done? Gfycat is still supported?

It stopped downloading now but the command printed "done, 1157 download links started!"

I suspect those links are gfycat links but I can't find their dl location. What does that line means anyway?

**Comment by DreamPhreak** [comment]
I'm pretty sure that "# download links started!" line is meant to say "# download links downloaded!".

**Comment by DreamPhreak** [comment]
Hey you're right. I sent the bot a gfycat link directly, it worked. I created a test server and posted the same link in the channel, (different download location too) and asked the bot to download it, and it skipped it. Posted a direct video .webm link and it got that one.

**Comment by Kakkela** [comment]
This was problem that was caused by earlier merge and has been fixed yesterday. It affected all the linked images in history downloading. Make sure you are running the latest version of the tool.

Also that 

> X download links started!

means just that, it tried to download this many links, it doesn't identify how many actually were downloaded.
