### ISSUE TITLE
I will Provide Help.

### ISSUE THREAD

**Issue by Stahlhelm-TV** [Seklfreak/discord-image-downloader-go#150]
You need help setting the program up?

Contact Me on discord: Stahlhelm_TV#2208

Already 25 people used my help so feel free to ask me

**Comment by beskhu3epnm** [comment]
I contacted this guy and he guided me through the solution to getting this running on my **GNU/Linux **Linux Mint**** OS. I had trouble using Wine to emulate the Windows version. I have summarized the guide below for your convenience.

- Download discord-image-downloader-go-linux-amd64
- In the file properties, go to _Permissions_ and mark the file to be run as a program
- Double-click to run the file. If a Terminal window doesn't open, open the Terminal and type `sudo '/location/discord-image-downloader-go-linux-amd64'` _(replace `/location/` with the actual location of the file on your computer)_. It should create a file called 'config.ini' in that same directory.
- Create a second Discord account if you don't already have one. Should be able to do this in within 5-10 minutes with a throwaway email. I used [https://www.emailondeck.com](https://www.emailondeck.com)
- Log in with your second throwaway account in your browser. Send a direct message to your primary account. You can say anything. Have your main account logged in with the main Discord app.
- Open the 'config.ini' file and edit some of the text. If you are just using the script to download from Discord, you can delete the Flickr and Twitter sections. **Enter the email and password information in the relevant fields for your **throwaway** Discord account.**
- Open the settings in Discord, and under 'Appearance', turn on Developer Mode. This will add new options when you **right-click on channels and DMs to **copy the ID****. Paste that ID underneath '[channels]' in the config.ini file, and after '=' put the directory you wish to save the images in.
- **Under the '[interactive channels]' heading, **place the ID for the DM between you and the throwaway account****. Also put the save directory after the '=' again. It can be the same directory as above.
- Now save the config file, and run the script again with `sudo '/location/discord-image-downloader-go-linux-amd64'`. It will start searching for links and outputting the information in the terminal. Check your save folder to see if media is being downloaded.

Below is an example of how your config.ini file might look:
```
[auth]
email    = webby1@wwfontslel.com
password = thisismypassword_12345

[general]
skip edits                           = true
download tistory sites               = false
max download retries                 = 5
download timeout                     = 60
send notices to interactive channels = false

[channels]
600197625586238938 = /home/user/Desktop/NewFolder

[interactive channels]
662661447244486362 = /home/user/Desktop/NewFolder
```

It would be convenient if a video tutorial was made to explain this process. I was almost dissuaded from installing this because I ran into issues which discouraged me.

**Comment by drachedachte1** [comment]
drache GRaf#8675

if the maker dosent make a discord server i will do it

**Comment by EnesCK-V1** [comment]
how do i run this on raspberry pi 2
