### ISSUE TITLE
401 Error even with the discord user token

### ISSUE THREAD

**Issue by accpi** [Seklfreak/discord-image-downloader-go#95]
![image](https://user-images.githubusercontent.com/15874826/41366504-4b419e8a-6f0a-11e8-8c2a-bdd76b8999a2.png)

Used the token method and was still getting this error: 

HTTP 401 Unauthorized, <?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>
done, 0 download links started!

Tried with only email/pw, email/pw/token, token and they all gave me the same error.

Made sure to take out the "" from the token copied from the discord.

**Comment by ranbeer2004** [comment]
Can you help me out in  this coz I am facing the same issue

**Comment by drachedachte1** [comment]
@ranbeer2004 @accpi 
Why is there a / in the channel id?
![image](https://user-images.githubusercontent.com/65346683/102598267-0a24b680-411c-11eb-955e-083f34173d25.png)

U prob need to verify ur acc with mobile or get the new token (discord changes the token of a normal acc so that might be the problem) or its bc the bot dosent have access to the channel (i dont think its that but ye not sure)

Unofficial Support Server
https://discord.gg/d8MYEC6

**Comment by drachedachte1** [comment]
you need to make a new channel download path for every single id 
u cant have multible in one paragraph
